# Generated by Django 3.2.21 on 2023-11-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phon', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phon', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='s_product_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='')),
                ('fdate', models.DateField()),
                ('tdate', models.DateField()),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phon', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='subsidy_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sproduct', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.officer')),
            ],
        ),
        migrations.CreateModel(
            name='subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('FERTILIZER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='sorder_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.s_product_request')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.subsidy_product')),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phon', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='request_schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.farmer')),
                ('SCHEMES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.schemes')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.product')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.order')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.user'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='SHOPS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.shops'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='LOGINID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.login_table'),
        ),
        migrations.CreateModel(
            name='doubts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.farmer')),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.officer')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.user')),
            ],
        ),
    ]
