# Generated by Django 3.2.21 on 2023-11-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='request_schemes',
        ),
    ]
